### ISSUE TITLE
Been trying to use it but it is not working with these errors

### ISSUE THREAD

**Issue by solnsumei** [TheDOme6/device_id#3]
- error: Value for SWIFT_VERSION cannot be empty. (in target 'device_id')
- Does it require any permission on IOS?

**Comment by SarcasticNoodle** [comment]
I only have Windows and Linux so I can only test my code on android, but I think this can help: https://stackoverflow.com/questions/46338588/xcode-9-swift-language-version-swift-version

**Comment by SarcasticNoodle** [comment]
#4
