### ISSUE TITLE
"device_id" file not found

### ISSUE THREAD

**Issue by Eric-Yoo-OBIGO** [TheDOme6/device_id#4]
Xcode's output:
↳
    === BUILD TARGET device_id OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/baeksunyu/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/device_id-0.1.3/ios/Classes/DeviceIdPlugin.m:2:9: fatal error: 'device_id/device_id-Swift.h' file not found
    #import <device_id/device_id-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by SarcasticNoodle** [comment]
https://github.com/flutter/flutter/issues/18673#issuecomment-441029307

**Comment by SarcasticNoodle** [comment]
#2

**Comment by nishit7777** [comment]
There is an issue in your pod file. **Please update your pod file**
Add This line:: **use_frameworks! #**
Before **ENV['COCOAPODS_DISABLE_STATS'] = 'true'**
Save pod file and Run your project it should be built.
