### ISSUE TITLE
Generate different ID everytime I reinstall app

### ISSUE THREAD

**Issue by krunaldodiya** [TheDOme6/device_id#7]
Hi, I am not getting unique I'd but it keep generating different his everytime I install apk, it happens in some particular device only, other device work fine. For example Samsung galaxy A50, android PIE

**Comment by SarcasticNoodle** [comment]
https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID
"Note: For apps that were installed prior to updating the device to a version of Android 8.0 (API level 26) or higher, the value of ANDROID_ID changes if the app is uninstalled and then reinstalled after the OTA. To preserve values across uninstalls after an OTA to Android 8.0 or higher, developers can use Key/Value Backup."

**Comment by krunaldodiya** [comment]
I am not aware of this key/value backup ?? can you please provide some example how to use?
