### ISSUE TITLE
'device_id` does not specify a Swift version

### ISSUE THREAD

**Issue by thethirdtomas** [TheDOme6/device_id#9]
`device_id` does not specify a Swift version and none of the targets
    (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please
    contact the author or set the `SWIFT_VERSION` attribute in at least one of
    the targets that integrate this pod.

**Comment by amrud** [comment]
still getting same error

**Comment by jonsamwell** [comment]
@amrud Add the following line to the top of your podfile

```ENV['SWIFT_VERSION'] = '4.2'```
